version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/su-kun1899/furikake
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
